[package]
name = "drebbel"
version = "0.1.0"
authors = ["John P Mayer Jr <john.p.mayer.jr@gmail.com>"]

[[bin]]
name = "drebbel"

[lib]
name = "drebbel"

[build-dependencies]
lalrpop = "0.13"

[dependencies]
linefeed = "0.2"
lalrpop-util = "0.13"
regex = "0.2"